export const SETUSERDATA = 'SETUSERDATA';
export const DELETEUSERDATA = 'DELETEUSERDATA';
export const SETISLOGGEDIN = 'SETISLOGGEDIN';
export const SETISLOGGEDOUT = 'SETISLOGGEDOUT';
export const EDITUSERDATA = 'EDITUSERDATA';
export const ADDTOCART = 'ADDTOCART';
export const REMOVECART = 'REMOVECART';
export const CARTDRAWER = "CARTDRAWER";



